### ISSUE TITLE
魅族手机

### ISSUE THREAD

**Issue by ghost** [meizuosc/m571#6]
把开放BootLoader的通道弄了吧，内核源码和驱动也开源了吧，看看现在的用户体验，bug还是有，官方修复能力有限，再者，看看15 16 x8  note8  note9等这些高通soc的机器，安卓版本还在8.1，flyme8都还不清楚更不更新底层，你们掉其他厂商老远了，哪怕是为了这些用户，你也应该开源了。你们若真有能力，就应该最大限度的修复bug，更快去更新底层，你一个优化都弄不好，试问，这手机销量怎么上的去？

**Comment by blackrow67** [comment]
LoL Meizu LoL
